// Generated by https://quicktype.io

export interface ClientesResponse {
    statusCode:    number;
    isExistoso:    boolean;
    errorMessages: any[];
    resultado:     Cliente[];
}

export interface Cliente {
    idCliente: number;
    documento: string;
    nombre:    string;
    apellido:  string;
    telefono:  string;
    estado:    boolean;
}

// Generated by https://quicktype.io

export interface PedidosResponse {
    statusCode:    number;
    isExistoso:    boolean;
    errorMessages: any[];
    resultado:     Pedido[];
}

export interface Pedido {
    idPedido:            number;
    idCliente:           number;
    idClienteNavigation: IDClienteNavigation;
    idEstado:            number;
    idEstadoNavigation:  IDEstadoNavigation;
    fechaPedido:         string;
    fechaEntrega:        string;
}

export interface IDClienteNavigation {
    idCliente: number;
    documento: string;
    nombre:    string;
    apellido:  string;
    telefono:  string;
    estado:    boolean;
}

export interface IDEstadoNavigation {
    idEstado:    number;
    nombre:      string;
    descripcion: string;
}

// Generated by https://quicktype.io

export interface DetallesResponse {
    statusCode:    number;
    isExistoso:    boolean;
    errorMessages: any[];
    resultado:     Detalle[];
}

export interface Detalle {
    idDetallePedido:      number;
    idPedido:             number;
    idPedidoNavigation:   IDPedidoNavigation;
    idEmpleado:           number;
    idEmpleadoNavigation: IDEmpleadoNavigation;
    idEstado:             number;
    idEstadoNavigation:   IDEstadoNavigation;
    nombreAnillido:       string;
    servicio:                 string;
    peso:                 string;
    tamanoAnillo:         string;
    tamanoPiedra:         string;
    material:             string;
    detalle:              string;
    cantidad:             number;
    motivoDevolucion:     null | string;
}

export interface IDEmpleadoNavigation {
    idEmpleado:          number;
    idUsuario:           number;
    idUsuarioNavigation: null;
    estado:              boolean;
    documento:           string;
    nombre:              string;
    apellido:            string;
    cargo:               string;
}

export enum Descripcion {
    ElPedidoHaSidoEntregado = "El pedido ha sido entregado",
    ElPedidoNoHaSidoIniciado = "El pedido no ha sido iniciado",
    ElPedidoSEEncuentraEnProceso = "El pedido se encuentra en proceso",
}

export enum Nombre {
    EnProduccion = "En produccion",
    Entregado = "Entregado",
    Recibido = "Recibido",
}

export interface IDPedidoNavigation {
    idPedido:            number;
    idCliente:           number;
    idClienteNavigation: IDClienteNavigation;
    idEstado:            number;
    idEstadoNavigation:  IDEstadoNavigation;
    fechaPedido:         string;
    fechaEntrega:        string;
}

// Generated by https://quicktype.io
export interface LoginData {
    correo: string;
    contrasena: string;
}

export interface LoginResponse {
    statusCode:    number;
    isExistoso:    boolean;
    errorMessages: any[];
    resultado:     LoginResult;
}

export interface LoginResult {
    isExitoso: boolean;
    token:     string;
}
