// Generated by https://quicktype.io

export interface ClientesResponse {
    statusCode:    number;
    isExistoso:    boolean;
    errorMessages: any[];
    resultado:     Cliente[];
}

export interface Cliente {
    idCliente: number;
    documento: string;
    nombre:    string;
    apellido:  string;
    telefono:  string;
    estado:    boolean;
}
